### ISSUE TITLE
Using Chessfloor stutters while rotating Robot, if chess floor is updated before the rotation is complete

### ISSUE THREAD

**Issue by DragonflyPlay11** [orat/EuclidView3d#17]
Updating the chess floor before updating the robot/skeleton leads to the rotation having stutters. Also having smaller squares slows down the rotating performance, this performance issues is a framerate drop. (at least at 50.f size). 
For now: First update the robot (with update parameter false) then update the chessfloor (with update paramter true).

**Comment by orat** [comment]
works fine
